export const WRITING_LESSONS = [
  {
    id: "missing-period-1",
    title: "The Missing Period",
    description: "Restore the first magical sentence.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "missing-punctuation",
    xp: 5,
    sentence: "The dragon found a magical book",
    choices: [".", "?", "!"],
    answer: ".",
    successMessage: "The first magical sentence has been restored!",
  },
  {
    id: "missing-question-1",
    title: "The Missing Question Mark",
    description: "Questions have lost their punctuation.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "missing-punctuation",
    xp: 5,
    sentence: "Where did the wizard hide the scroll",
    choices: [".", "?", "!"],
    answer: "?",
    prerequisite: "missing-period-1",
    successMessage: "The question magic has returned!",
  },
  {
    id: "missing-exclamation-1",
    title: "The Missing Exclamation Mark",
    description: "Exciting sentences need powerful punctuation.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "missing-punctuation",
    xp: 5,
    sentence: "The castle doors opened with a flash of light",
    choices: [".", "?", "!"],
    answer: "!",
    prerequisite: "missing-question-1",
    successMessage: "The sentence now shines with excitement!",
  },
  {
    id: "missing-capital-1",
    title: "The Missing Capital Letter",
    description: "Every sentence needs a strong beginning.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "missing-capital",
    xp: 5,
    sentence: "___ princess opened the royal library.",
    choices: ["the", "The"],
    answer: "The",
    prerequisite: "missing-exclamation-1",
    successMessage: "The royal scroll shines brighter!",
},
];