export const WRITING_LESSONS = [
  {
    id: "missing-period-1",
    title: "The Missing Period",
    description: "Restore the first magical sentence.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "missing-punctuation",
    xp: 5,
    sentence: "The dragon found a magical book",
    choices: [".", "?", "!"],
    answer: ".",
    successMessage: "The first magical sentence has been restored!",
    bookId: "dragon-journal",
    pageNumber: 1,  
  },
  {
    id: "missing-question-1",
    title: "The Missing Question Mark",
    description: "Questions have lost their punctuation.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "missing-punctuation",
    xp: 5,
    sentence: "Where did the wizard hide the scroll",
    choices: [".", "?", "!"],
    answer: "?",
    prerequisite: "missing-period-1",
    successMessage: "The question magic has returned!",
    bookId: "dragon-journal",
    pageNumber: 2,
  },
  {
    id: "missing-exclamation-1",
    title: "The Missing Exclamation Mark",
    description: "Exciting sentences need powerful punctuation.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "missing-punctuation",
    xp: 5,
    sentence: "The castle doors opened with a flash of light",
    choices: [".", "?", "!"],
    answer: "!",
    prerequisite: "missing-question-1",
    successMessage: "The sentence now shines with excitement!",
    bookId: "dragon-journal",
    pageNumber: 3,
  },
  {
    id: "missing-capital-1",
    title: "The Missing Capital Letter",
    description: "Every sentence needs a strong beginning.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "missing-capital",
    xp: 5,
    sentence: "___ princess opened the royal library.",
    choices: ["the", "The"],
    answer: "The",
    prerequisite: "missing-exclamation-1",
    successMessage: "The royal scroll shines brighter!",
    bookId: "dragon-journal",
    pageNumber: 4,
},
{
    id: "missing-word-1",
    title: "The Missing Word",
    description: "A magical sentence is missing one important word.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "missing-word",
    xp: 5,
    sentence: "The knight rode a ___ horse.",
    choices: ["blue", "quickly", "under"],
    answer: "blue",
    prerequisite: "missing-capital-1",
    successMessage: "The sentence is whole again!",
    bookId: "dragon-journal",
    pageNumber: 5,
},
    {
    id: "sentence-order-1",
    title: "The Broken Sentence",
    description: "The words have fallen out of order.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "sentence-ordering",
    xp: 10,
    words: ["The", "wizard", "opened", "the", "book."],
    answer: "The wizard opened the book.",
    prerequisite: "missing-word-1",
    successMessage: "The sentence has been rebuilt!",
    bookId: "dragon-journal",
    pageNumber: 6,  
    },

    {
    id: "grammar-choice-1",
    title: "The Royal Grammar Test",
    description: "Choose the word that makes the sentence correct.",
    difficulty: "Easy",
    realm: "Royal Library",
    activityType: "grammar-choice",
    xp: 10,
    prompt: "Which word belongs in the sentence?",
    sentence: "The dragons ___ flying over the castle.",
    choices: ["is", "are"],
    answer: "are",
    prerequisite: "sentence-order-1",
    successMessage: "The royal grammar spell is working again!",
    bookId: "dragon-journal",
    pageNumber: 7,
    },
];